### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by RM35M4419** [robertmartin8/KindleClippings#3]
Hi Robert, your script was exactly what I needed.

I just got this error from a particular book with a huge subtitle.

I added this lines at the end of the _remove_chars_ method to fix it (after line 24):
```
# Clip the file names that are too long
if len(s) > 100:
    s = s[:100]
```
Supposedly the max file length is 255 chars, but I think it includes the path. 

Cheers!

**Comment by robertmartin8** [comment]
@RM35M4419 

I'm glad you found the script useful! I have just pushed the fix. As a small python note, the `if` statement isn't needed – you can just do `s = s[:100]` and for smaller `s` the string will be unchanged.

Best,
Robert
